name: Default Workflow

on:
  - push
  - workflow_dispatch

jobs:
  deploy:
    runs-on: deployment
    defaults:
      run:
        working-directory: /opt/home-assistant-microsoft-teams-presence/
    steps:      
      - run: |
          git pull
